package com.astracare.core.data.di

import android.content.Context
import androidx.room.Room
import com.astracare.core.data.database.AstraCareDatabase
import com.astracare.core.data.database.DATABASE_NAME
import com.astracare.core.data.database.dao.BeneficiaryDao
import com.astracare.core.data.database.dao.DraftDao
import com.astracare.core.data.database.dao.SyncStateDao
import com.astracare.core.data.database.migration.ALL_MIGRATIONS
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

/**
 * Constructs the database and exposes its DAOs.
 *
 * `@Provides` rather than `@Binds` because [AstraCareDatabase] is abstract and generated by
 * Room — it must be built, not merely aliased.
 *
 * `@Singleton` matters here more than most places: a `RoomDatabase` owns a connection pool and
 * a write lock. Two instances against the same file means two pools competing for that lock,
 * which produces intermittent `SQLITE_BUSY` failures under concurrent access — exactly the
 * conditions a background sync worker writing while the UI reads creates.
 *
 * `@ApplicationContext`, not an Activity context: the database outlives every screen, and
 * holding an Activity context in a singleton is a textbook leak.
 */
@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    @Provides
    @Singleton
    fun providesDatabase(
        @ApplicationContext context: Context,
    ): AstraCareDatabase {
        val builder = Room.databaseBuilder(
            context = context,
            klass = AstraCareDatabase::class.java,
            name = DATABASE_NAME,
        )
        // Registered from a single list in the migration package, so adding a migration is
        // one edit there rather than two. A migration that exists but is never registered is
        // the classic way a correct migration still crashes on upgrade.
        ALL_MIGRATIONS.forEach { builder.addMigrations(it) }
        return builder.build()
    }
    // Note the absence of fallbackToDestructiveMigration(). It is the usual quick fix for a
    // schema change and it works by DELETING the database. On an app whose entire purpose is
    // holding data that has not reached a server yet, that is silent, unrecoverable field data
    // loss on upgrade. Schema changes here get a real migration — see the migration package,
    // and DECISION_LOG 6.3.

    /**
     * Exposing the DAO separately means consumers depend on the narrow interface they use
     * rather than on the whole database. `OfflineFirstBeneficiaryRepository` takes a
     * [BeneficiaryDao], so a test can supply an in-memory Room instance's DAO — or a fake —
     * without constructing anything else.
     */
    @Provides
    fun providesBeneficiaryDao(database: AstraCareDatabase): BeneficiaryDao =
        database.beneficiaryDao()

    @Provides
    fun providesDraftDao(database: AstraCareDatabase): DraftDao = database.draftDao()

    @Provides
    fun providesSyncStateDao(database: AstraCareDatabase): SyncStateDao =
        database.syncStateDao()
}
