package com.astracare.core.data.di

import android.content.Context
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.astracare.core.data.crypto.DatabasePassphrase
import com.astracare.core.data.database.AstraCareDatabase
import com.astracare.core.data.database.DATABASE_NAME
import com.astracare.core.data.database.dao.AuditDao
import com.astracare.core.data.database.dao.BeneficiaryDao
import com.astracare.core.data.database.dao.DraftDao
import com.astracare.core.data.database.dao.SessionDao
import com.astracare.core.data.database.dao.SyncStateDao
import com.astracare.core.data.database.migration.ALL_MIGRATIONS
import com.astracare.core.data.database.migration.createAuditLogTriggers
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import net.zetetic.database.sqlcipher.SupportOpenHelperFactory
import javax.inject.Singleton

/**
 * Constructs the database and exposes its DAOs.
 *
 * `@Provides` rather than `@Binds` because [AstraCareDatabase] is abstract and generated by
 * Room — it must be built, not merely aliased.
 *
 * `@Singleton` matters here more than most places: a `RoomDatabase` owns a connection pool and
 * a write lock. Two instances against the same file means two pools competing for that lock,
 * which produces intermittent `SQLITE_BUSY` failures under concurrent access — exactly the
 * conditions a background sync worker writing while the UI reads creates.
 *
 * `@ApplicationContext`, not an Activity context: the database outlives every screen, and
 * holding an Activity context in a singleton is a textbook leak.
 */
@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    /**
     * ## The database is encrypted, and nothing above this module knows that
     *
     * `openHelperFactory` swaps the SQLite implementation Room writes through. Every DAO,
     * every query, every migration is unchanged — which is the whole reason the encryption
     * decision could be deferred to Day 16 and still be one file's worth of change. It also
     * means removing it is one line.
     *
     * Three details that are easy to get wrong:
     *
     *  - **`System.loadLibrary` first.** SQLCipher is a native library and nothing in it works
     *    until the `.so` is in the process. Missing it produces an `UnsatisfiedLinkError` from
     *    inside Room, on the first query rather than here.
     *  - **The modern artifact.** `net.zetetic:sqlcipher-android` uses
     *    `System.loadLibrary("sqlcipher")`. The older `net.zetetic:android-database-sqlcipher`
     *    — still what most tutorials show — wants `SQLiteDatabase.loadLibs(context)` instead,
     *    and mixing the two coordinates is a duplicate-native-symbol crash.
     *  - **The passphrase is not zeroed.** [SupportOpenHelperFactory] keeps the array it is
     *    given and offers no way to clear it; the `clearPassphrase` flag belonged to the older
     *    artifact. Zeroing it here is not possible either, because the factory opens the
     *    database lazily and may reopen it later. So the passphrase lives in heap memory for
     *    the life of the process, which is a real limit on what this protects against and is
     *    written down as one rather than glossed. See DECISION_LOG 10.5.
     */
    @Provides
    @Singleton
    fun providesDatabase(
        @ApplicationContext context: Context,
        passphrase: DatabasePassphrase,
    ): AstraCareDatabase {
        System.loadLibrary(SQLCIPHER_LIBRARY)

        val builder = Room.databaseBuilder(
            context = context,
            klass = AstraCareDatabase::class.java,
            name = DATABASE_NAME,
        ).openHelperFactory(SupportOpenHelperFactory(passphrase.get()))
            .addCallback(auditLogTriggerCallback)

        // Registered from a single list in the migration package, so adding a migration is
        // one edit there rather than two. A migration that exists but is never registered is
        // the classic way a correct migration still crashes on upgrade.
        ALL_MIGRATIONS.forEach { builder.addMigrations(it) }
        return builder.build()
    }
    // Note the absence of fallbackToDestructiveMigration(). It is the usual quick fix for a
    // schema change and it works by DELETING the database. On an app whose entire purpose is
    // holding data that has not reached a server yet, that is silent, unrecoverable field data
    // loss on upgrade. Schema changes here get a real migration — see the migration package,
    // and DECISION_LOG 6.3.

    /**
     * Exposing the DAO separately means consumers depend on the narrow interface they use
     * rather than on the whole database. `OfflineFirstBeneficiaryRepository` takes a
     * [BeneficiaryDao], so a test can supply an in-memory Room instance's DAO — or a fake —
     * without constructing anything else.
     */
    @Provides
    fun providesBeneficiaryDao(database: AstraCareDatabase): BeneficiaryDao =
        database.beneficiaryDao()

    @Provides
    fun providesDraftDao(database: AstraCareDatabase): DraftDao = database.draftDao()

    @Provides
    fun providesSyncStateDao(database: AstraCareDatabase): SyncStateDao =
        database.syncStateDao()

    @Provides
    fun providesAuditDao(database: AstraCareDatabase): AuditDao = database.auditDao()

    @Provides
    fun providesSessionDao(database: AstraCareDatabase): SessionDao = database.sessionDao()

    /**
     * Installs the append-only triggers on a database Room has just created.
     *
     * The half of the guarantee a migration cannot provide. Room builds a fresh schema from the
     * compiled `@Entity` classes and runs no migration at all, and `@Entity` cannot declare a
     * trigger — so without this, `audit_log` would be append-only on upgraded devices and
     * silently mutable on every new install. Room does not validate triggers either, so nothing
     * would have reported the gap.
     *
     * `onCreate`, not `onOpen`: the statements are idempotent, but running two `CREATE TRIGGER`
     * calls on every single app launch is work for nothing.
     */
    private val auditLogTriggerCallback = object : RoomDatabase.Callback() {
        override fun onCreate(db: SupportSQLiteDatabase) {
            createAuditLogTriggers(db)
        }
    }

    /** The native library name, which is not the artifact name and not the class name. */
    private const val SQLCIPHER_LIBRARY = "sqlcipher"
}
